---

- name: Reload systemd daemon and restart litellm service.
  ansible.builtin.systemd:
    name: litellm
    state: restarted
    daemon_reload: true
  listen: "restart litellm"

- name: Reload systemd daemon and restart headroom service.
  ansible.builtin.systemd:
    name: headroom
    state: restarted
    daemon_reload: true
  listen: "restart headroom"
