---

namespace: tesseract
name: app
version: 1.0.0
readme: README.md
authors:
  - Ben Wadsworth
description: Ansible roles for managing application configurations and services for tesseract.
license:
  - Unlicense
license_file: 'LICENSE'
repository: https://github.com/ben16w/tesseract-app
dependencies: {}
tags:
  - linux
  - infrastructure
build_ignore:
  - .ansible
  - .venv
  - .drone.yml
  - .gitignore
  - requirements.txt
