---

namespace: tesseract
name: app
version: 1.0.0
readme: README.md
authors:
- ben16w
description: null
license:
- Unlicense
license_file: 'LICENSE'
repository: https://github.com/ben16w/tesseract-app
