all:
  hosts:
    192.168.56.11

  vars:
    ansible_connection: ssh
    ansible_user: "vagrant"
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: "/usr/bin/python3"

    tesseract_username: vagrant

    dashboard_apps:
      - name: Nextcloud
        target: "https://docs.gengar.lan"
        icon: nextcloud.png
      - name: Jellyfin
        target: "https://watch.gengar.lan"
        icon: jellyfin.png

    dashboard_admin_apps:
      - name: Netdata
        icon: netdata.png
        target:
          - http://gengar.lan:19999
          - http://onix.lan:19999
          - http://tepig.lan:19999
          - http://charizard.lan:19999