---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - comfyui_rocm_version_short is not none
      - comfyui_rocm_version_long is not none

- name: Check if the distribution is Ubuntu.
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'Ubuntu'

- name: Ensure render and video groups exist.
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop:
    - render
    - video

- name: Add the tesseract user to the render and video groups.
  ansible.builtin.user:
    name: "{{ tesseract_username }}"
    groups:
      - render
      - video
    append: true

- name: Install necessary Linux headers and modules.
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - "linux-modules-extra-{{ ansible_kernel }}"
    state: present
    update_cache: true

- name: Download the AMDGPU driver package.
  ansible.builtin.get_url:
    url: "https://repo.radeon.com/amdgpu-install/\
      {{ comfyui_rocm_version_short }}/ubuntu/\
      {{ ansible_distribution_release }}/amdgpu-install_\
      {{ comfyui_rocm_version_long }}_all.deb"
    dest: /tmp/amdgpu-install.deb
    owner: root
    group: root
    mode: '0644'
  register: download_driver
  retries: 5
  delay: 10
  until: download_driver is succeeded

- name: Install the AMDGPU driver package.
  ansible.builtin.apt:
    deb: /tmp/amdgpu-install.deb

- name: Run amdgpu-install script to finalize installation.
  ansible.builtin.command:
    cmd: "amdgpu-install --usecase=graphics,rocm --accept-eula -y"
  changed_when: false
