---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - comfyui_version is not none
      - not ((comfyui_use_cpu | bool) and (comfyui_use_rocm | bool))
      - not ((comfyui_enable_manager_legacy_ui | bool) and not (comfyui_enable_manager | bool))

- name: Ensure tesseract user exists.
  register: tesseract_user_details
  ansible.builtin.user:
    name: "{{ tesseract_username }}"

- name: Ensure required system packages are installed.
  ansible.builtin.package:
    name:
      - acl
      - git
      - python3
      - python3-pip
      - python3-venv
      - wget
    state: present
    update_cache: true

- name: Create ComfyUI directory.
  ansible.builtin.file:
    path: /opt/comfyui
    state: directory
    owner: "{{ tesseract_username }}"
    group: "{{ tesseract_username }}"
    mode: '0755'

- name: Clone ComfyUI repository.
  ansible.builtin.git:
    repo: https://github.com/comfyanonymous/ComfyUI.git
    dest: /opt/comfyui
    version: "{{ comfyui_version }}"
    force: true
  become: true
  become_user: "{{ tesseract_username }}"
  notify: restart comfyui

- name: Install PyTorch for AMD ROCm.
  when: comfyui_use_rocm is true
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/rocm6.2 --no-cache-dir"
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install PyTorch for CPU.
  when: comfyui_use_cpu is true
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/cpu --no-cache-dir"
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install ComfyUI requirements.
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    requirements: /opt/comfyui/requirements.txt
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install ComfyUI manager requirements.
  when: comfyui_enable_manager | bool
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    requirements: /opt/comfyui/manager_requirements.txt
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Deploy systemd service.
  ansible.builtin.template:
    src: templates/comfyui.service.j2
    dest: /etc/systemd/system/comfyui.service
    owner: root
    group: root
    mode: '0644'
  notify: restart comfyui

- name: Enable and start ComfyUI service.
  ansible.builtin.systemd:
    name: comfyui
    enabled: true
    state: started

- name: Set ComfyUI Manager config settings.
  when: comfyui_enable_manager | bool
  ansible.builtin.lineinfile:
    path: /opt/comfyui/user/__manager/config.ini
    search_string: "{{ item.search }}"
    line: "{{ item.line }}"
  loop:
    - search: "security_level ="
      line: "security_level = {{ comfyui_manager_security_level }}"
    - search: "network_mode ="
      line: "network_mode = {{ comfyui_manager_network_mode }}"
  register: result
  retries: 10
  delay: 3
  until: result is not failed
  notify: restart comfyui
