---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - comfyui_version is not none
      - not ((comfyui_use_cpu | bool) and (comfyui_use_rocm | bool))
      - not ((comfyui_enable_manager_legacy_ui | bool) and not (comfyui_enable_manager | bool))

- name: Ensure tesseract user exists.
  register: tesseract_user_details
  ansible.builtin.user:
    name: "{{ tesseract_username }}"

- name: Ensure required system packages are installed.
  ansible.builtin.package:
    name:
      - acl
      - git
      - python3
      - python3-pip
      - python3-venv
      - wget
    state: present
    update_cache: true

- name: Create ComfyUI directory.
  ansible.builtin.file:
    path: /opt/comfyui
    state: directory
    owner: "{{ tesseract_username }}"
    group: "{{ tesseract_username }}"
    mode: '0755'

- name: Clone ComfyUI repository.
  ansible.builtin.git:
    repo: https://github.com/comfyanonymous/ComfyUI.git
    dest: /opt/comfyui
    version: "{{ comfyui_version }}"
    force: true
  become: true
  become_user: "{{ tesseract_username }}"
  notify: restart comfyui

- name: Install PyTorch for AMD ROCm.
  when: comfyui_use_rocm is true
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/rocm6.2 --no-cache-dir"
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install PyTorch for CPU.
  when: comfyui_use_cpu is true
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/cpu --no-cache-dir"
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install ComfyUI requirements.
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    requirements: /opt/comfyui/requirements.txt
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Install ComfyUI manager requirements.
  when: comfyui_enable_manager | bool
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.pip:
    requirements: /opt/comfyui/manager_requirements.txt
    virtualenv: /opt/comfyui/venv
    virtualenv_command: python3 -m venv
    state: present
  notify: restart comfyui

- name: Ensure ComfyUI manager configuration directory exists.
  when: comfyui_enable_manager | bool
  ansible.builtin.file:
    path: /opt/comfyui/user/__manager
    state: directory
    owner: "{{ tesseract_username }}"
    group: "{{ tesseract_username }}"
    mode: '0755'

- name: Deploy ComfyUI manager configuration.
  when: comfyui_enable_manager | bool
  ansible.builtin.template:
    src: templates/manager-config.ini.j2
    dest: /opt/comfyui/user/__manager/config.ini
    owner: "{{ tesseract_username }}"
    group: "{{ tesseract_username }}"
    mode: '0644'
    force: false
  notify: restart comfyui

- name: Create cron job to restart ComfyUI service.
  ansible.builtin.cron:
    name: "Restart ComfyUI service"
    job: /bin/systemctl restart comfyui.service
    minute: "0"
    hour: "{{ comfyui_restart_cron_hour }}"
    state: "{{ 'present' if comfyui_restart_cron_enabled else 'absent' }}"

- name: Deploy systemd service.
  ansible.builtin.template:
    src: templates/comfyui.service.j2
    dest: /etc/systemd/system/comfyui.service
    owner: root
    group: root
    mode: '0644'
  notify: restart comfyui

- name: Enable and start ComfyUI service.
  ansible.builtin.systemd:
    name: comfyui
    enabled: true
    state: started
    daemon_reload: true
