---
- name: Converge
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: "{{ tesseract_username }}"
        password: '*'
        shell: /bin/bash
        home: /home/{{ tesseract_username }}
        state: present
        createhome: true
        update_password: on_create
