---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Verify Influxdb is serving web requests.
      ansible.builtin.uri:
        url: "http://localhost:{{ scrutiny_influxdb_port }}"
        status_code: 200

    - name: Verify Scrutiny is serving web requests.
      ansible.builtin.uri:
        url: "http://localhost:{{ scrutiny_ui_port }}"
        status_code: 200

    - name: Verify the Scrutiny collector runs successfully.
      ansible.builtin.command:
        cmd: "/opt/scrutiny/bin/scrutiny-collector-metrics run --api-endpoint 'http://localhost:{{ scrutiny_ui_port }}'"
      register: scrutiny_collector_output
      failed_when: scrutiny_collector_output.rc != 0
      changed_when: false
