---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Verify Influxdb is serving web requests.
      ansible.builtin.uri:
        url: "http://localhost:{{ scrutiny_influxdb_port }}"
        status_code: 200

    - name: Verify Scrutiny is serving web requests.
      ansible.builtin.uri:
        url: "http://localhost:{{ scrutiny_ui_port }}"
        status_code: 200
