---
- name: Converge
  hosts: all
  vars:
    ollama_port: 8080
    ollama_models:
      - name: TinyLlama
        url: "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/\
          resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
  roles:
    - role: ollama
