---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
    - vars.yml
  tasks:
    - name: Check that netdata service is running.
      ansible.builtin.systemd:
        name: netdata
      register: netdata_service
      failed_when: netdata_service.status.ActiveState != 'active'

    - name: Check netdata API is serving requests.
      ansible.builtin.uri:
        url: http://localhost:{{ netdata_port }}/api/v1/info
        return_content: true
        status_code: 200
      register: netdata_info

    - name: Assert netdata API returned version information.
      ansible.builtin.assert:
        that:
          - netdata_info.json.version is defined
