---

tesseract_username: "tesseract"

tesseract_hostname: ~
tesseract_domain: ~

docker_apps: []

tesseract_email_username: ~
tesseract_email_host: ~
tesseract_email_port: ~
tesseract_email_password: ~

docker_data_paths: []
  # - name: example
  #   path: /mnt/example
docker_appdata_path: ~

docker_compose_repo: https://github.com/ben16w/tesseract-common.git
docker_compose_version: main
docker_compose_path: /opt/common
docker_compose_subdir: compose

docker_project_name: "tesseract"

docker_default_username: "ben"
docker_default_password: "password"
docker_tz: "Europe/London"

docker_extra_compose_files: []

docker_extra_vars: {}
  # example_name: "example_value"

docker_autostart_disabled: false
