---

# https://learn.netdata.cloud/guides/configure/performance

- name: Install curl and msmtp.
  ansible.builtin.apt:
    pkg:
      - msmtp
      - curl
    update_cache: true

- name: When monitoring_emails are disabled.
  when: monitoring_email_disabled is false
  block:

    - name: Assert that all required inputs have been provided.
      ansible.builtin.assert:
        that:
          - email_host is not none
          - email_port is not none
          - email_username is not none
          - email_password is not none

    - name: Add msmtp email global config.
      no_log: true
      ansible.builtin.blockinfile:
        path: /etc/msmtprc
        create: true
        owner: root
        group: root
        mode: '0644'
        block: |
          account default
          tls on
          tls_starttls off
          tls_certcheck off
          auth login
          host "{{ email_host }}"
          port "{{ email_port }}"
          user "{{ email_username }}"
          from "{{ email_username }}"
          password "{{ email_password }}"

- name: Download netdata install script.
  retries: 3
  delay: 10
  ansible.builtin.get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/netdata_install.sh
    owner: root
    group: root
    mode: '0744'
    force: false

- name: Install netdata using downloaded script.
  notify: restart netdata
  ansible.builtin.command:
    cmd: bash /tmp/netdata_install.sh --dont-wait
    creates: /usr/sbin/netdata

# FIXME This is not working
# - name: Reduce netdata data collection frequency to 5 seconds.
#   notify: restart netdata
#   ansible.builtin.lineinfile:
#     path: /etc/netdata/netdata.conf
#     insertafter: "[global]"
#     line: "update every = 5"
#     firstmatch: yes

# there may be multiple "bind to"
# Destination /etc/netdata/netdata.conf does not exist on 32bit Raspbian
- name: Set netdata to listen of all interfaces.
  notify: restart netdata
  ansible.builtin.lineinfile:
    path: /etc/netdata/netdata.conf
    search_string: bind to =
    line: bind to = *

- name: Copy health_alarm_notify.conf if it doesn't exist.
  ansible.builtin.copy:
    src: /usr/lib/netdata/conf.d/health_alarm_notify.conf
    dest: /etc/netdata/health_alarm_notify.conf
    remote_src: true
    force: false
    owner: root
    group: root
    mode: '0644'

- name: Set netdata to use msmtp for email.
  notify: restart netdata
  ansible.builtin.lineinfile:
    path: /etc/netdata/health_alarm_notify.conf
    search_string: sendmail=
    line: "sendmail='/usr/bin/msmtp'"

- name: When monitoring_emails are disabled.
  when: monitoring_email_disabled is false
  block:

    - name: Set netdata email sender.
      notify: restart netdata
      ansible.builtin.lineinfile:
        path: /etc/netdata/health_alarm_notify.conf
        search_string: EMAIL_SENDER=
        line: "EMAIL_SENDER='{{ email_username }}'"

    - name: Set netdata email recipient.
      notify: restart netdata
      ansible.builtin.lineinfile:
        path: /etc/netdata/health_alarm_notify.conf
        search_string: DEFAULT_RECIPIENT_EMAIL=
        line: "DEFAULT_RECIPIENT_EMAIL='{{ email_username }}|critical'"

- name: Claim netdata node.
  when: netdata_token is not none and netdata_rooms is not none
  ansible.builtin.command:
    cmd: /usr/libexec/netdata/netdata-claim.sh -token={{ netdata_token }} -rooms={{ netdata_rooms }}
    creates: /var/lib/netdata/cloud.d/claim.conf
  notify: restart netdata
