---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - vagrant_virtualbox_version is not none

- name: Set architecture variable.
  ansible.builtin.set_fact:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Ensure gpg-agent is installed.
  ansible.builtin.apt:
    name: gpg-agent
    state: present
    update_cache: true

- name: Add an Apt signing key for 2016 virtualbox.
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add virtualbox repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }}] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: true

- name: Install virtualbox
  ansible.builtin.apt:
    pkg:
      - "virtualbox-{{ vagrant_virtualbox_version }}"

- name: Add an Apt signing key for vagrant.
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add vagrant repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install vagrant.
  ansible.builtin.apt:
    pkg:
      - vagrant
