---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - vagrant_virtualbox_version is not none

- name: Set architecture variable.
  ansible.builtin.set_fact:
    arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"

- name: Install python3-debian for deb822_repository.
  ansible.builtin.apt:
    name: python3-debian
    state: present
    update_cache: true

- name: Add VirtualBox repository.
  ansible.builtin.deb822_repository:
    name: virtualbox
    types: deb
    uris: https://download.virtualbox.org/virtualbox/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: contrib
    architectures: "{{ arch }}"
    signed_by: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present

- name: Install virtualbox.
  ansible.builtin.apt:
    pkg:
      - "virtualbox-{{ vagrant_virtualbox_version }}"
    update_cache: true

- name: Add HashiCorp repository.
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    architectures: "{{ arch }}"
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    state: present

- name: Install vagrant.
  ansible.builtin.apt:
    pkg:
      - vagrant
    update_cache: true
