---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - vagrant_virtualbox_version is not none

- name: Set architecture variable.
  ansible.builtin.set_fact:
    arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"

- name: Ensure gpg-agent is installed.
  ansible.builtin.apt:
    name: gpg-agent
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings directory exists.
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download VirtualBox signing key.
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /etc/apt/keyrings/virtualbox.asc
    mode: '0644'

- name: Add virtualbox repository into sources list
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch }} signed-by=/etc/apt/keyrings/virtualbox.asc]
      https://download.virtualbox.org/virtualbox/debian
      {{ ansible_facts['distribution_release'] }} contrib
    state: present
    update_cache: true

- name: Install virtualbox
  ansible.builtin.apt:
    pkg:
      - "virtualbox-{{ vagrant_virtualbox_version }}"

- name: Download Hashicorp signing key.
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: '0644'

- name: Add vagrant repository into sources list
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch }} signed-by=/etc/apt/keyrings/hashicorp.asc]
      https://apt.releases.hashicorp.com
      {{ ansible_facts['distribution_release'] }} main
    state: present
    update_cache: true

- name: Install vagrant.
  ansible.builtin.apt:
    pkg:
      - vagrant
