---
- name: Install Steam
  ansible.builtin.include_tasks: install_steam.yml

- name: Install Gamescope
  ansible.builtin.include_tasks: install_gamescope.yml

- name: Install Sunshine
  ansible.builtin.include_tasks: install_sunshine.yml

- name: Configure Steam streaming
  ansible.builtin.include_tasks: configure.yml
