---
- name: Converge
  hosts: all
  vars:
    litellm_port: 4000
    litellm_master_key: "sk-1234"
    litellm_models:
      - model_name: mock
        litellm_params:
          model: mock/model
  roles:
    - role: litellm
