---
- name: Verify
  hosts: all
  vars:
    litellm_port: 3000
    litellm_master_key: "sk-1234"
    litellm_models:
      - model_name: mock
        litellm_params:
          model: mock/model
  tasks:

    - name: Check binary exists in venv.
      ansible.builtin.stat:
        path: /opt/litellm/venv/bin
      register: litellm_bin
      failed_when: not litellm_bin.stat.exists

    - name: Check service is running.
      ansible.builtin.service:
        name: litellm
        state: started
      register: service_status
      failed_when: not service_status.state == 'started'

    - name: Check LiteLLM is listening on the correct port.
      ansible.builtin.wait_for:
        port: "{{ litellm_port }}"
        state: started
        timeout: 10
      register: port_check
      failed_when: not port_check.elapsed < 10

    - name: List models expecting failure without API key.
      ansible.builtin.uri:
        url: "http://localhost:{{ litellm_port }}/models"
        method: GET
        return_content: true
      register: model_list_response
      failed_when: model_list_response.status == 200

    - name: List models with master key.
      ansible.builtin.uri:
        url: "http://localhost:{{ litellm_port }}/models"
        method: GET
        return_content: true
        headers:
          Authorization: "Bearer {{ litellm_master_key }}"
      register: model_list_response_key
      failed_when: model_list_response_key.status != 200
