---
steam_user: steam
steam_group: steam
steam_home: "/home/{{ steam_user }}"
steam_service_name: steam-stream
steam_resolution: 1920x1080
steam_framerate: 60
steam_enable_i386_architecture: true
steam_manage_sunshine_state: true
steam_packages:
  - steam-installer
  - sunshine
  - gamescope
  - mesa-vulkan-drivers
  - mesa-vulkan-drivers:i386
  - libgl1-mesa-dri
  - libgl1-mesa-dri:i386
  - libegl1-mesa
  - libegl1-mesa:i386
  - libgbm1
  - libgbm1:i386
  - libva2
  - libva2:i386
  - libpipewire-0.3-0
  - pipewire
  - pipewire-pulse
  - wireplumber
  - xwayland
  - xdg-desktop-portal
  - xdg-user-dirs
  - dbus-user-session
  - pulseaudio-utils
  - psmisc
  - procps
  - sudo
steam_prerequisite_packages:
  - software-properties-common
  - apt-transport-https
  - ca-certificates
