---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
  - name: Verify Syncthing is serving web requests.
    ansible.builtin.uri:
      url: "http://localhost:{{ syncthing_port }}"
      status_code: 200
