---

llama_cpp_version: "b10199"
llama_cpp_port: 8080
llama_cpp_models:
  - name: smollm
    url: "https://huggingface.co/QuantFactory/SmolLM-135M-GGUF/resolve/main/\
      SmolLM-135M.Q4_K_M.gguf"
llama_cpp_context_length: 2048
