---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
    - vars.yml
  tasks:
    - name: Check llama.cpp version is correct.
      ansible.builtin.command:
        cmd: llama-server --version
      register: llama_cpp_version_check
      failed_when: llama_cpp_version not in llama_cpp_version_check.stdout
      changed_when: false

    - name: Check llama-server health endpoint.
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ llama_cpp_port }}/health"
        method: GET
        status_code: 200
      register: health_response
      failed_when: health_response.json.status != 'ok'

    - name: Generate a response from the model.
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ llama_cpp_port }}/v1/chat/completions"
        method: POST
        body_format: json
        timeout: 120
        body:
          model: "{{ llama_cpp_models[0].name }}.gguf"
          messages:
            - role: user
              content: "Why is the sky blue?"
          stream: false
      register: generate_response
      failed_when: generate_response.status != 200
