---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Check if port 9090 is responding
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ cockpit_port }}"
        state: started
        timeout: 10
      register: result

    - name: Fail if Cockpit is not running on port 9090
      ansible.builtin.fail:
        msg: "Cockpit is not running on port 9090"
      when: result is failed

    - name: Check Cockpit Web UI
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:9090"
        status_code: 200
      register: response

    - name: Fail if Cockpit Web UI is not accessible
      ansible.builtin.fail:
        msg: "Cockpit Web UI is not accessible"
      when: response.status not in [200, 301, 302]
