---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Check if Cockpit UI is running on port 9090
      ansible.builtin.wait_for:
        host: localhost
        port: 9090
        state: started
        timeout: 10
      register: result

    - name: Fail if Cockpit UI is not running on port 9090
      ansible.builtin.fail:
        msg: "Cockpit UI is not running on port 9090"
      when: not result.is_failed
