---

tesseract_username: "tesseract"

mcp_proxy_version: ~ # e.g. "0.43.2"

mcp_proxy_port: 9090
mcp_proxy_base_url: "http://127.0.0.1:{{ mcp_proxy_port }}"
mcp_proxy_transport_type: streamable-http

mcp_proxy_panic_if_invalid: false
mcp_proxy_log_enabled: true

mcp_proxy_npm_packages: []
# Example:
# mcp_proxy_npm_packages:
#   - "@modelcontextprotocol/server-github@2025.4.8"

mcp_proxy_servers: {}
# Example:
# mcp_proxy_servers:
#   github:
#     command: "npx"
#     args:
#       - "-y"
#       - "@modelcontextprotocol/server-github@2025.4.8"
#     env:
#       GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_PERSONAL_ACCESS_TOKEN}"
#   fetch:
#     command: "uvx"
#     args:
#       - "mcp-server-fetch"
