---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - tesseract_username is not none
      - tesseract_domain is not none

- name: Ensure tesseract user exists.
  register: tesseract_user_details
  ansible.builtin.user:
    name: "{{ tesseract_username }}"

- name: Run tasks when Booksonic is enabled
  ansible.builtin.include_tasks:
    file: booksonic.yml
  when: app_tweaks_enable_booksonic is true

- name: Run tasks when Nextcloud is enabled.
  ansible.builtin.include_tasks:
    file: nextcloud.yml
  when: app_tweaks_enable_nextcloud is true

- name: Run tasks when Steam is enabled.
  ansible.builtin.include_tasks:
    file: steam.yml
  when: app_tweaks_enable_steam is true

- name: Run tasks when Steam C-state limit is enabled.
  ansible.builtin.include_tasks:
    file: steam_cstates.yml
  when: app_tweaks_enable_steam_cstates is true

- name: Run tasks when Transmission is enabled.
  ansible.builtin.include_tasks:
    file: transmission.yml
  when: app_tweaks_enable_transmission is true

- name: Run tasks when Jenkins is enabled.
  ansible.builtin.include_tasks:
    file: jenkins.yml
  when: app_tweaks_enable_jenkins is true

- name: Run tasks when Drone CI is enabled.
  ansible.builtin.include_tasks:
    file: drone.yml
  when: app_tweaks_enable_drone is true
