---

- name: Install cron and linux-cpupower.
  ansible.builtin.package:
    name:
      - cron
      - linux-cpupower
    update_cache: true
  when: ansible_distribution != 'Ubuntu'

- name: Install cron and linux-tools for the current kernel (Ubuntu only).
  ansible.builtin.package:
    name:
      - cron
      - linux-tools-common
      - linux-tools-generic
      - "linux-tools-{{ ansible_kernel }}"
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: Create scripts directory if it does not exist.
  ansible.builtin.file:
    path: "{{ tesseract_files_path }}/scripts"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Template cstates-limit.sh script to scripts directory.
  ansible.builtin.template:
    src: templates/cstates-limit.sh.j2
    dest: "{{ tesseract_files_path }}/scripts/cstates-limit.sh"
    owner: root
    group: root
    mode: '0755'

- name: Create cron job to limit C-states for Steam.
  ansible.builtin.cron:
    name: "Limit C-states for Steam."
    special_time: reboot
    job: "bash {{ tesseract_files_path }}/scripts/cstates-limit.sh"
