---
- name: Converge
  hosts: all
  vars:
    tesseract_username: tesseract
    tesseract_hostname: docker-test
    tesseract_domain: example.test
    tesseract_email_username: alerts@example.test
    tesseract_email_host: smtp.example.test
    tesseract_email_port: "465"
    tesseract_email_password: password
    docker_data_paths:
      - name: media
        path: /srv/docker/media
    docker_appdata_path: /srv/docker/appdata
    docker_apps: []
  roles:
    - role: tesseract.app.docker
