---
- name: Converge
  hosts: all
  vars:
    tesseract_username: "root"
    tesseract_domain: "example.com"
    app_tweaks_enable_nextcloud: true
    app_tweaks_enable_jenkins: true
    app_tweaks_enable_drone: true
    app_tweaks_drone_rpc_secret: "ABDC1234"
  roles:
    - role: app_tweaks
