---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
    - vars.yml
  tasks:
    - name: Verify drone-runner-exec service is running.
      ansible.builtin.service:
        name: drone-runner-exec
        state: started
      register: service_status
      failed_when: service_status.changed

    - name: Verify gitea-mcp binary is installed.
      ansible.builtin.stat:
        path: /usr/local/bin/gitea-mcp
      register: gitea_mcp_binary
      failed_when: not gitea_mcp_binary.stat.exists
