---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Run cstate-limit.sh script on host and check if there's any errors.
      ansible.builtin.command:
        cmd: "bash {{ tesseract_files_path }}/scripts/cstate-limit.sh -d"
      register: cstate_limit

    - name: Fail if cstate-limit.sh script returned any errors.
      ansible.builtin.fail:
        msg: "cstate-limit.sh script returned errors."
      when: cstate_limit.rc != 0

    - name: Verify drone-runner-exec service is running.
      ansible.builtin.service:
        name: drone-runner-exec
        state: started
      register: service_status

    - name: Fail if service was started.
      ansible.builtin.fail:
        msg: "Service drone-runner-exec was changed."
      when: service_status.changed
