---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - mcp_proxy_version is not none
      - mcp_proxy_transport_type in ['sse', 'streamable-http']
      - mcp_proxy_servers is defined
      - mcp_proxy_servers is mapping

- name: Set architecture variable.
  ansible.builtin.set_fact:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Ensure tesseract user exists.
  ansible.builtin.user:
    name: "{{ tesseract_username }}"

- name: Ensure tar is installed.
  ansible.builtin.package:
    name:
      - tar
    state: present
    update_cache: true

- name: Ensure mcp-proxy directory exists.
  ansible.builtin.file:
    path: /opt/mcp-proxy
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install npm packages for npx MCP servers.
  ansible.builtin.include_tasks: npm.yml
  when: mcp_proxy_npm_packages | length > 0

- name: Download mcp-proxy archive.
  ansible.builtin.get_url:
    url: "https://github.com/tbxark/mcp-proxy/releases/download/v{{ mcp_proxy_version }}/\
      mcp-proxy_{{ mcp_proxy_version }}_linux_{{ arch }}.tar.gz"
    dest: "/tmp/mcp-proxy.tar.gz"
    mode: '0744'
    owner: root
    group: root
  register: download_mcpproxy
  retries: 5
  delay: 10
  until: download_mcpproxy is succeeded

- name: Unarchive mcp-proxy from archive.
  notify: restart mcp_proxy
  ansible.builtin.unarchive:
    src: "/tmp/mcp-proxy.tar.gz"
    dest: /opt/mcp-proxy/
    remote_src: true
    creates: "/opt/mcp-proxy/mcp-proxy"
    owner: root
    group: root
    mode: '0755'

- name: Template the mcp-proxy config file.
  notify: restart mcp_proxy
  ansible.builtin.template:
    src: templates/config.json.j2
    dest: /opt/mcp-proxy/config.json
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd service.
  notify: restart mcp_proxy
  ansible.builtin.template:
    src: templates/mcp-proxy.service.j2
    dest: /etc/systemd/system/mcp-proxy.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start mcp-proxy.
  ansible.builtin.systemd:
    name: mcp-proxy
    enabled: true
    state: started
