---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - tesseract_username is not none
      - tesseract_password is not none

- name: Ensure gpg-agent is installed.
  ansible.builtin.apt:
    name:
      - gpg-agent
    state: present
    update_cache: true

- name: Add an Apt signing key for syncthing.
  ansible.builtin.apt_key:
    url: "{{ syncthing_key }}"
    state: present

- name: Add syncthing repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ syncthing_repo }}"
    state: present
    update_cache: true

- name: Install syncthing.
  ansible.builtin.apt:
    pkg:
      - syncthing

- name: Set GUI password.
  become: true
  become_user: "{{ tesseract_username }}"
  ansible.builtin.command:
    cmd: >
      syncthing generate
        --config="{{ syncthing_config_dir }}"
        --gui-password="{{ tesseract_password }}"
        --gui-user="{{ tesseract_username }}"
    creates: "{{ syncthing_config_dir }}/config.xml"
  notify: restart syncthing

- name: Open syncthing GUI to all.
  ansible.builtin.lineinfile:
    path: "{{ syncthing_config_dir }}/config.xml"
    search_string: <address>127.0.0.1:8384</address>
    line: "<address>0.0.0.0:{{ syncthing_port }}</address>"
    owner: "{{ tesseract_username }}"
    group: "{{ tesseract_username }}"
    mode: '0600'
  notify: restart syncthing

- name: Start syncthing service.
  ansible.builtin.service:
    name: syncthing@{{ tesseract_username }}.service
    enabled: true
    state: started
